### ISSUE TITLE
how exactly does the color method on Embeds work?

### ISSUE THREAD

**Issue by Blastbrean** [thoo0224/webhook-rs#19]
are we supposed to pass in a hex value, rgb? there is no documentation or example on this method.

**Comment by i1Fury** [comment]
Hey! I did some testing, and it takes the hex code of whatever color you want, converted to a decimal, then to a string.

1. FF5555
2. 16733525
3. "16733525"

You probably moved on from this problem a long time ago haha but im putting this here for anyone else who may have the same question!

**Comment by Blastbrean** [comment]
Thank you so much! Sadly, it's a bit late since I switched to Go and PocketBase to have a websocket end-point. Still, it will help in my other projects.
