### ISSUE TITLE
Feature for tokio/reqwest

### ISSUE THREAD

**Issue by MOZGIII** [thoo0224/webhook-rs#2]
I'd like to use just the message type from this crate, but it still pulls the `tokio`, `reqwest`, and a whole bunch of other stuff I don't use as dependencies.

It would be great if the `Webhook` type and all the networking-related dependencies were behind a feature, that I could disable via `default-features = false` in my `Cargo.toml`.

**Comment by thoo0224** [comment]
types and networking-related dependencies will be separated with features in the recoded version.
